/*
 * generated by Xtext
 */
package csep.example.cake.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CakefileUiModule extends csep.example.cake.ui.AbstractCakefileUiModule {
	public CakefileUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
