/*
 * generated by Xtext
 */
package csep.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CoffeeScriptUiModule extends csep.ui.AbstractCoffeeScriptUiModule {
	public CoffeeScriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
