/*
 * generated by Xtext
 */
package csep.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.resource.IGlobalServiceProvider;
import org.eclipse.xtext.ui.editor.autoedit.AbstractEditStrategyProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;

import csep.ui.autoedit.AutoEditStrategyProvider;
import csep.ui.hover.NullSafeResourceServiceProvider;
import csep.ui.syntaxcoloring.AntlrTokenToAttributeIdMapper;
import csep.ui.syntaxcoloring.LexicalHighlightingConfiguration;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CoffeeScriptUiModule extends csep.ui.AbstractCoffeeScriptUiModule {
	public CoffeeScriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends IHighlightingConfiguration> bindIHighlightingConfiguration() {
		return LexicalHighlightingConfiguration.class;
	}

	public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
		return AntlrTokenToAttributeIdMapper.class;
	}
	
	@Override
	public Class<? extends AbstractEditStrategyProvider> bindAbstractEditStrategyProvider() {
		return AutoEditStrategyProvider.class;
	}
	
	public Class<? extends IGlobalServiceProvider> bindIGlobalServiceProvider() {
		return NullSafeResourceServiceProvider.class;
	}
}
