/*
* generated by Xtext
*/
package csep.example.cake.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class CakefileOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
