/*
* generated by Xtext
*/
package csep.ui.contentassist;

import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

import csep.coffeeScript.Application;
import csep.coffeeScript.IdRef;

public class CoffeeScriptProposalProvider extends AbstractCoffeeScriptProposalProvider {
	private final static String[] COMMON_FEATURES = new String[]{
		"constructor",
		"toString()",
		"valueOf()",
	};
	
	public void completeProperty_Prop(Application model, Assignment assignment, ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		super.completeProperty_Prop(model, assignment, context, acceptor);
		IdRef idRef = (IdRef)model.getValue();
		String idName = idRef.getVal().getName();
		for (String proposal: COMMON_FEATURES) {
			acceptor.accept(createCompletionProposal(proposal, context));
		}
		String proposal = idName + "Dummy";
		acceptor.accept(createCompletionProposal(proposal, context));
	}
}
