/*
* generated by Xtext
*/
package csep.ui.contentassist;

import csep.ui.contentassist.AbstractCoffeeScriptProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CoffeeScriptProposalProvider extends AbstractCoffeeScriptProposalProvider {

}
