/*
* generated by Xtext
*/
package csep.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class CoffeeScriptOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
