/*
* generated by Xtext
*/
package csep.example.cake.ui.contentassist;

import csep.example.cake.ui.contentassist.AbstractCakefileProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CakefileProposalProvider extends AbstractCakefileProposalProvider {

}
