/*
 * generated by Xtext
 */
package csep.example.cake;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CakefileRuntimeModule extends csep.example.cake.AbstractCakefileRuntimeModule {

}
